# Generated by Django 4.0.4 on 2022-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('document_description', models.CharField(max_length=200)),
                ('is_sent', models.BooleanField()),
                ('is_received', models.BooleanField()),
                ('date_sent', models.DateTimeField()),
                ('document_content', models.FileField(upload_to='')),
            ],
        ),
    ]
