# Generated by Django 4.0.4 on 2022-11-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_document_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_description',
            field=models.TextField(),
        ),
    ]
