# Generated by Django 4.0.4 on 2022-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_document_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
