# Generated by Django 4.0.4 on 2022-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_document_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
