# Generated by Django 4.0.4 on 2022-11-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_alter_document_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
