# Generated by Django 4.0.4 on 2022-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_alter_document_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_received',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_sent',
            field=models.BooleanField(null=True),
        ),
    ]
