# Generated by Django 4.0.4 on 2022-11-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_alter_document_is_received_alter_document_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_content',
            field=models.FileField(null=True, upload_to='../static/files/'),
        ),
    ]
